apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flask
  labels:
    run: flask
spec:
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: quay.io/kubernetes-for-developers/flask:0.1.1
          resources:
          limits:
            memory: "40Mi"
            cpu: "500m"
          requests:
            memory: "40Mi"
            cpu: "500m"
          ports:
            - containerPort: 5000
